### ISSUE TITLE
Issues with Addon-actions.

### ISSUE THREAD

**Issue by Westbrook** [open-wc/storybook-prebuilt#4]
When using addon-actions, both when running storybook live and when visiting a built preview, I get errors when attempting to publish actions into the knobs panel. 

Errors exhibit like the following:
![image](https://user-images.githubusercontent.com/1156657/74789275-a3feb580-52f7-11ea-9677-2130ed2708f4.png)

and tracking to the line in `rng.js` I find the following code.

```
var crypto = require('crypto');

module.exports = function nodeRNG() {
  return crypto.randomBytes(16);
};
```

There is no `crypto` package in my `node_modules` so I assume that it's talking about the node.js native `crypto` package which wouldn't be available in a browser and would need to be addressed by building that code into this file, or by altering the dependency here to something currently available in the project `crypt`, etc.

**Comment by Westbrook** [comment]
I'll have to look closer at what this means as far as versions in this repo, but it appears that this started somewhere between `v1.8.3` and `v1.9.5` or `@open-wc/demoing-storybook`...

**Comment by Westbrook** [comment]
So it looks like `uuid` vends a browser version of the file in question: https://github.com/uuidjs/uuid/blob/master/src/rng-browser.js, but it doesn't look like any of their exported files actually point to it. It _may_ be that what is needed here is for prebuilt to use an extended application of the `replace` plug-in in the Rollup config in order to ensure that the file we want here is used? I'm in a super low connectivity environment, so I'm not able to test this directly until the beginning of next week, but I'll take other suggestions in the mean time.

**Comment by LarsDenBakker** [comment]
This might be related to the way in our build process we resolve this module. I wonder if there is a difference between webpack and rollup here?

Is this a node built-in library?

**Comment by benjamind** [comment]
Is the browser option set for the rollup plugin node resolve?

https://github.com/rollup/plugins/blob/master/packages/node-resolve/README.md#browser
